
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 02 22:27:36 CET 2017
//----------------------------------------------------

package Calc;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int _INTEGER_ = 8;
}

